spring:
  application:
    name: Student
  datasource:
    url: jdbc:mysql://localhost:3306/StudentDB
    username: root
    password: root
#    $env:DB_PASSWORD="your_password_here"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

